src/accounts/urls.py
from django.conf.urls import url

from .views import login_view, logout_view, UserRegisterView, UserDetailView, UserFollowView

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^register/$', UserRegisterView.as_view(), name='register'),
    url(r'^(?P<username>[\w.]+)/$', UserDetailView.as_view(), name='detail'),
    url(r'^(?P<username>[\w.]+)/follow/$', UserFollowView.as_view(), name='follow'),
]

src/blogger/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.conf.urls import url
from .views import home_page_view

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',home_page_view, name='home'),
    url(r'^blogs/',include('blogs.urls',namespace='blogs')),
    url(r'^accounts/',include('accounts.urls', namespace='accounts')),
    url(r'^api-auth/', include('rest_framework.urls')),
]

src/blogs/urls.py
from django.conf.urls import url

from .views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = 'blogs'

urlpatterns = [
    url(r'^$',BlogListView.as_view(), name='list'),
    url(r'^(?P<pk>[0-9]+)/$',BlogDetailView.as_view(), name='detail'),
    url(r'^create/$',BlogCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/update/$',BlogUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete/$',BlogDeleteView.as_view(), name='delete'),
]

src/templates/snippets/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home' %}">
    <img src="https://upload.wikimedia.org/wikipedia/commons/3/31/Blogger.svg" width="30" height="30" class="d-inline-block align-top" alt="">
    Blog
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blogs:list' %}">Blogs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blogs:create' %}">Create</a>
      </li>
      {% if request.path == '/blogs/' %}
      <form class="form-inline" action="{% url 'blogs:list' %}" method="GET">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name='q' value="{{ request.GET.q }}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      {% endif %}
    </ul>

    {% if request.user.is_authenticated %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:detail' username=request.user.username %}">{{ request.user.username }}</a>
      </li>
    </ul>
    {% else %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:login' %}?next={{ request.path }}">LogIn</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
      </li>
    </ul>
    {% endif %}
  </div>
</nav>